"""
Central course catalog. The Flask API, the ML training scripts, the
recommendation engine, career roadmaps, skill-gap analysis, interview
prep and placement model all import this so every feature stays in sync
with a single source of truth.
"""

COURSES = [
    {
        "id": "AIML", "name": "AI & Machine Learning", "credits": 4,
        "min_cgpa": 7.5, "max_backlog": 0, "last_date": "Aug 10, 2026", "seats": 60,
        "tags": ["ai", "machine learning", "neural networks", "python", "deep learning", "data"],
        "department": "Computer Science",
        "skills_taught": ["Python", "Machine Learning", "Deep Learning", "Neural Networks", "Statistics"],
        "career_paths": ["ML Engineer", "AI Researcher", "Data Scientist"],
        "employability_index": 0.90,
    },
    {
        "id": "DS", "name": "Data Science", "credits": 4,
        "min_cgpa": 7.0, "max_backlog": 1, "last_date": "Aug 10, 2026", "seats": 60,
        "tags": ["data", "analytics", "statistics", "python", "visualization", "sql"],
        "department": "Computer Science",
        "skills_taught": ["Python", "SQL", "Statistics", "Data Visualization", "Pandas"],
        "career_paths": ["Data Analyst", "Data Scientist", "BI Analyst"],
        "employability_index": 0.85,
    },
    {
        "id": "WEB", "name": "Web Development", "credits": 3,
        "min_cgpa": 6.0, "max_backlog": 2, "last_date": "Aug 15, 2026", "seats": 80,
        "tags": ["web", "frontend", "backend", "javascript", "react", "html", "css"],
        "department": "Computer Science",
        "skills_taught": ["HTML", "CSS", "JavaScript", "React", "Node.js", "REST APIs"],
        "career_paths": ["Frontend Developer", "Full-Stack Developer", "Web Engineer"],
        "employability_index": 0.78,
    },
    {
        "id": "CYB", "name": "Cyber Security", "credits": 4,
        "min_cgpa": 7.0, "max_backlog": 1, "last_date": "Aug 12, 2026", "seats": 50,
        "tags": ["security", "networking", "ethical hacking", "cryptography", "linux"],
        "department": "Computer Science",
        "skills_taught": ["Network Security", "Cryptography", "Ethical Hacking", "Linux", "Risk Analysis"],
        "career_paths": ["Security Analyst", "Penetration Tester", "SOC Engineer"],
        "employability_index": 0.83,
    },
    {
        "id": "CLOUD", "name": "Cloud Computing", "credits": 3,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 12, 2026", "seats": 55,
        "tags": ["cloud", "aws", "azure", "devops", "docker", "kubernetes", "infrastructure"],
        "department": "Computer Science",
        "skills_taught": ["AWS", "Docker", "Kubernetes", "CI/CD", "Linux"],
        "career_paths": ["Cloud Engineer", "DevOps Engineer", "Site Reliability Engineer"],
        "employability_index": 0.87,
    },
    {
        "id": "FULLSTACK", "name": "Full Stack Development", "credits": 4,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 14, 2026", "seats": 70,
        "tags": ["fullstack", "frontend", "backend", "javascript", "react", "node", "database", "api"],
        "department": "Computer Science",
        "skills_taught": ["React", "Node.js", "Express", "MongoDB", "REST APIs", "Git"],
        "career_paths": ["Full-Stack Developer", "Software Engineer", "Product Engineer"],
        "employability_index": 0.88,
    },
    {
        "id": "BACKEND", "name": "Backend Development", "credits": 4,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 14, 2026", "seats": 60,
        "tags": ["backend", "server", "api", "database", "python", "java", "microservices"],
        "department": "Computer Science",
        "skills_taught": ["Python", "Java", "SQL", "REST APIs", "System Design", "Microservices"],
        "career_paths": ["Backend Developer", "API Engineer", "Software Engineer"],
        "employability_index": 0.86,
    },
    {
        "id": "DEVOPS", "name": "DevOps Engineering", "credits": 4,
        "min_cgpa": 7.0, "max_backlog": 1, "last_date": "Aug 13, 2026", "seats": 45,
        "tags": ["devops", "ci/cd", "docker", "kubernetes", "automation", "infrastructure", "linux"],
        "department": "Computer Science",
        "skills_taught": ["Docker", "Kubernetes", "CI/CD", "Terraform", "Linux", "Jenkins"],
        "career_paths": ["DevOps Engineer", "Site Reliability Engineer", "Platform Engineer"],
        "employability_index": 0.89,
    },
    {
        "id": "ANALYTICS", "name": "Data & Business Analytics", "credits": 3,
        "min_cgpa": 6.0, "max_backlog": 2, "last_date": "Aug 16, 2026", "seats": 75,
        "tags": ["analytics", "business intelligence", "excel", "sql", "dashboards", "statistics", "data"],
        "department": "Computer Science",
        "skills_taught": ["Excel", "SQL", "Power BI", "Tableau", "Statistics", "Data Storytelling"],
        "career_paths": ["Business Analyst", "Data Analyst", "BI Developer"],
        "employability_index": 0.80,
    },
    {
        "id": "MOBILE", "name": "Mobile App Development", "credits": 3,
        "min_cgpa": 6.0, "max_backlog": 2, "last_date": "Aug 15, 2026", "seats": 55,
        "tags": ["mobile", "android", "ios", "flutter", "react native", "app"],
        "department": "Computer Science",
        "skills_taught": ["Flutter", "React Native", "Kotlin", "REST APIs", "UI Design"],
        "career_paths": ["Mobile Developer", "Android Engineer", "iOS Engineer"],
        "employability_index": 0.79,
    },
    {
        "id": "UIUX", "name": "UI/UX Design", "credits": 3,
        "min_cgpa": 5.5, "max_backlog": 2, "last_date": "Aug 16, 2026", "seats": 50,
        "tags": ["design", "ui", "ux", "figma", "prototyping", "user research"],
        "department": "Computer Science",
        "skills_taught": ["Figma", "Wireframing", "Prototyping", "User Research", "Design Systems"],
        "career_paths": ["UI Designer", "UX Designer", "Product Designer"],
        "employability_index": 0.75,
    },
    {
        "id": "BLOCKCHAIN", "name": "Blockchain & Web3", "credits": 3,
        "min_cgpa": 7.0, "max_backlog": 1, "last_date": "Aug 13, 2026", "seats": 35,
        "tags": ["blockchain", "web3", "solidity", "smart contracts", "crypto", "ethereum"],
        "department": "Computer Science",
        "skills_taught": ["Solidity", "Smart Contracts", "Ethereum", "Web3.js", "Cryptography"],
        "career_paths": ["Blockchain Developer", "Smart Contract Engineer", "Web3 Engineer"],
        "employability_index": 0.76,
    },
    {
        "id": "PHYSICS", "name": "Applied Physics", "credits": 3,
        "min_cgpa": 5.0, "max_backlog": 3, "last_date": "Aug 18, 2026", "seats": 100,
        "tags": ["physics", "mechanics", "electromagnetism", "thermodynamics", "science", "core"],
        "department": "Computer Science",
        "skills_taught": ["Classical Mechanics", "Electromagnetism", "Thermodynamics", "Problem Solving"],
        "career_paths": ["Research Assistant", "R&D Engineer", "Physics Educator"],
        "employability_index": 0.55,
    },
    {
        "id": "MATHS", "name": "Engineering Mathematics", "credits": 3,
        "min_cgpa": 5.0, "max_backlog": 3, "last_date": "Aug 18, 2026", "seats": 100,
        "tags": ["mathematics", "maths", "calculus", "algebra", "statistics", "core"],
        "department": "Computer Science",
        "skills_taught": ["Calculus", "Linear Algebra", "Probability", "Discrete Mathematics"],
        "career_paths": ["Quantitative Analyst", "Data Scientist", "Research Assistant"],
        "employability_index": 0.62,
    },
    {
        "id": "CPROG", "name": "C Programming", "credits": 3,
        "min_cgpa": 5.0, "max_backlog": 3, "last_date": "Aug 17, 2026", "seats": 90,
        "tags": ["c", "programming", "fundamentals", "systems", "memory"],
        "department": "Computer Science",
        "skills_taught": ["C", "Pointers", "Memory Management", "Debugging"],
        "career_paths": ["Systems Programmer", "Embedded Engineer", "Software Engineer"],
        "employability_index": 0.65,
    },
    {
        "id": "CPP", "name": "C++ Programming", "credits": 3,
        "min_cgpa": 5.5, "max_backlog": 2, "last_date": "Aug 17, 2026", "seats": 80,
        "tags": ["c++", "cpp", "oop", "programming", "systems", "competitive programming"],
        "department": "Computer Science",
        "skills_taught": ["C++", "OOP", "STL", "Data Structures"],
        "career_paths": ["Software Engineer", "Game Developer", "Competitive Programmer"],
        "employability_index": 0.72,
    },
    {
        "id": "JAVA", "name": "Java Programming", "credits": 3,
        "min_cgpa": 5.5, "max_backlog": 2, "last_date": "Aug 17, 2026", "seats": 85,
        "tags": ["java", "oop", "backend", "enterprise", "android"],
        "department": "Computer Science",
        "skills_taught": ["Java", "OOP", "Spring Boot", "JVM"],
        "career_paths": ["Java Developer", "Backend Engineer", "Android Developer"],
        "employability_index": 0.75,
    },
    {
        "id": "PYTHON", "name": "Python Programming", "credits": 3,
        "min_cgpa": 5.0, "max_backlog": 3, "last_date": "Aug 17, 2026", "seats": 100,
        "tags": ["python", "programming", "scripting", "automation", "fundamentals"],
        "department": "Computer Science",
        "skills_taught": ["Python", "OOP", "Scripting", "Automation"],
        "career_paths": ["Python Developer", "Automation Engineer", "Software Engineer"],
        "employability_index": 0.78,
    },
    {
        "id": "DSA", "name": "Data Structures & Algorithms", "credits": 4,
        "min_cgpa": 7.0, "max_backlog": 1, "last_date": "Aug 11, 2026", "seats": 70,
        "tags": ["dsa", "algorithms", "data structures", "competitive programming", "problem solving"],
        "department": "Computer Science",
        "skills_taught": ["Arrays", "Trees", "Graphs", "Dynamic Programming", "Algorithm Design"],
        "career_paths": ["Software Engineer", "SDE", "Competitive Programmer"],
        "employability_index": 0.88,
    },
    {
        "id": "FLASK", "name": "Flask Web Development", "credits": 3,
        "min_cgpa": 6.0, "max_backlog": 2, "last_date": "Aug 15, 2026", "seats": 60,
        "tags": ["flask", "python", "backend", "web", "api"],
        "department": "Computer Science",
        "skills_taught": ["Flask", "Python", "REST APIs", "SQLAlchemy", "Jinja2"],
        "career_paths": ["Backend Developer", "Python Web Developer", "API Engineer"],
        "employability_index": 0.76,
    },
    {
        "id": "FRONTEND", "name": "Frontend Development", "credits": 3,
        "min_cgpa": 5.5, "max_backlog": 2, "last_date": "Aug 16, 2026", "seats": 85,
        "tags": ["frontend", "react", "javascript", "html", "css", "ui"],
        "department": "Computer Science",
        "skills_taught": ["HTML", "CSS", "JavaScript", "React", "Responsive Design"],
        "career_paths": ["Frontend Developer", "UI Engineer", "Web Developer"],
        "employability_index": 0.77,
    },
    {
        "id": "SQL", "name": "SQL & Database Querying", "credits": 2,
        "min_cgpa": 5.0, "max_backlog": 3, "last_date": "Aug 18, 2026", "seats": 100,
        "tags": ["sql", "database", "query", "data"],
        "department": "Computer Science",
        "skills_taught": ["SQL", "Joins", "Indexing", "Query Optimization"],
        "career_paths": ["Database Developer", "Data Analyst", "Backend Developer"],
        "employability_index": 0.70,
    },
    {
        "id": "OOP", "name": "Object-Oriented Programming", "credits": 3,
        "min_cgpa": 5.5, "max_backlog": 2, "last_date": "Aug 17, 2026", "seats": 90,
        "tags": ["oop", "programming", "design patterns", "java", "c++"],
        "department": "Computer Science",
        "skills_taught": ["OOP", "Design Patterns", "Encapsulation", "Inheritance", "Polymorphism"],
        "career_paths": ["Software Engineer", "Application Developer"],
        "employability_index": 0.72,
    },
    {
        "id": "DBMS", "name": "Database Management Systems", "credits": 3,
        "min_cgpa": 6.0, "max_backlog": 2, "last_date": "Aug 16, 2026", "seats": 85,
        "tags": ["dbms", "database", "sql", "normalization", "transactions"],
        "department": "Computer Science",
        "skills_taught": ["DBMS", "Normalization", "SQL", "Transactions", "Indexing"],
        "career_paths": ["Database Administrator", "Backend Developer", "Data Engineer"],
        "employability_index": 0.74,
    },
    {
        "id": "SWE", "name": "Software Engineering", "credits": 3,
        "min_cgpa": 6.0, "max_backlog": 2, "last_date": "Aug 16, 2026", "seats": 90,
        "tags": ["software engineering", "sdlc", "agile", "testing", "design"],
        "department": "Computer Science",
        "skills_taught": ["SDLC", "Agile", "Testing", "Requirements Analysis", "UML"],
        "career_paths": ["Software Engineer", "QA Engineer", "Product Engineer"],
        "employability_index": 0.80,
    },
    {
        "id": "SYSDESIGN", "name": "System Design", "credits": 4,
        "min_cgpa": 7.5, "max_backlog": 0, "last_date": "Aug 11, 2026", "seats": 50,
        "tags": ["system design", "scalability", "architecture", "distributed systems"],
        "department": "Computer Science",
        "skills_taught": ["System Design", "Scalability", "Load Balancing", "Distributed Systems", "Caching"],
        "career_paths": ["Software Architect", "Senior SDE", "Backend Engineer"],
        "employability_index": 0.91,
    },
    {
        "id": "DOCKER", "name": "Docker & Containerization", "credits": 2,
        "min_cgpa": 6.0, "max_backlog": 2, "last_date": "Aug 15, 2026", "seats": 65,
        "tags": ["docker", "containers", "devops", "kubernetes"],
        "department": "Computer Science",
        "skills_taught": ["Docker", "Containerization", "Docker Compose", "Images"],
        "career_paths": ["DevOps Engineer", "Cloud Engineer", "Backend Developer"],
        "employability_index": 0.79,
    },
    {
        "id": "FASTAPI", "name": "FastAPI Web Development", "credits": 3,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 14, 2026", "seats": 55,
        "tags": ["fastapi", "python", "backend", "api", "async"],
        "department": "Computer Science",
        "skills_taught": ["FastAPI", "Python", "Async Programming", "REST APIs", "Pydantic"],
        "career_paths": ["Backend Developer", "API Engineer", "Python Developer"],
        "employability_index": 0.81,
    },
    {
        "id": "GENAI", "name": "Generative AI", "credits": 4,
        "min_cgpa": 7.5, "max_backlog": 0, "last_date": "Aug 10, 2026", "seats": 50,
        "tags": ["generative ai", "genai", "llm", "prompt engineering", "transformers"],
        "department": "Computer Science",
        "skills_taught": ["LLMs", "Prompt Engineering", "Transformers", "Fine-tuning", "RAG"],
        "career_paths": ["AI Engineer", "ML Engineer", "GenAI Developer"],
        "employability_index": 0.92,
    },
    {
        "id": "ML", "name": "Machine Learning", "credits": 4,
        "min_cgpa": 7.0, "max_backlog": 1, "last_date": "Aug 11, 2026", "seats": 65,
        "tags": ["machine learning", "ml", "supervised learning", "python", "statistics"],
        "department": "Computer Science",
        "skills_taught": ["Python", "Supervised Learning", "Unsupervised Learning", "Model Evaluation", "Scikit-learn"],
        "career_paths": ["ML Engineer", "Data Scientist", "Applied Scientist"],
        "employability_index": 0.89,
    },
    {
        "id": "DATAANALYTICS", "name": "Data Analytics", "credits": 3,
        "min_cgpa": 6.0, "max_backlog": 2, "last_date": "Aug 16, 2026", "seats": 90,
        "tags": ["data analytics", "analytics", "statistics", "excel", "visualization"],
        "department": "Computer Science",
        "skills_taught": ["Excel", "SQL", "Statistics", "Data Visualization", "Python"],
        "career_paths": ["Data Analyst", "Business Analyst", "Reporting Analyst"],
        "employability_index": 0.77,
    },
    {
        "id": "IOT", "name": "Internet of Things", "credits": 3,
        "min_cgpa": 6.0, "max_backlog": 2, "last_date": "Aug 15, 2026", "seats": 55,
        "tags": ["iot", "internet of things", "embedded", "sensors", "microcontrollers"],
        "department": "Computer Science",
        "skills_taught": ["Embedded C", "Sensors", "Microcontrollers", "MQTT", "Edge Computing"],
        "career_paths": ["IoT Engineer", "Embedded Systems Engineer", "Hardware Engineer"],
        "employability_index": 0.73,
    },
    {
        "id": "DWDM", "name": "Data Warehousing & Data Mining", "credits": 3,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 14, 2026", "seats": 60,
        "tags": ["data warehousing", "data mining", "etl", "olap", "big data"],
        "department": "Computer Science",
        "skills_taught": ["ETL", "OLAP", "Data Mining", "Clustering", "Association Rules"],
        "career_paths": ["Data Engineer", "BI Developer", "Data Warehouse Analyst"],
        "employability_index": 0.75,
    },
    {
        "id": "OS", "name": "Operating Systems", "credits": 4,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 12, 2026", "seats": 90,
        "tags": ["operating systems", "os", "processes", "memory management", "concurrency"],
        "department": "Computer Science",
        "skills_taught": ["Process Scheduling", "Memory Management", "Concurrency", "File Systems", "Threads"],
        "career_paths": ["Systems Engineer", "Kernel Developer", "Backend Engineer"],
        "employability_index": 0.80,
    },
    {
        "id": "ACA", "name": "Advanced Computer Architecture", "credits": 4,
        "min_cgpa": 7.0, "max_backlog": 1, "last_date": "Aug 11, 2026", "seats": 45,
        "tags": ["computer architecture", "pipelining", "cache", "parallel computing"],
        "department": "Computer Science",
        "skills_taught": ["Pipelining", "Cache Optimization", "Parallel Computing", "Instruction Sets"],
        "career_paths": ["Hardware Engineer", "Performance Engineer", "Systems Architect"],
        "employability_index": 0.74,
    },
    {
        "id": "DAA", "name": "Design & Analysis of Algorithms", "credits": 4,
        "min_cgpa": 7.5, "max_backlog": 0, "last_date": "Aug 10, 2026", "seats": 60,
        "tags": ["algorithms", "daa", "complexity analysis", "greedy", "divide and conquer"],
        "department": "Computer Science",
        "skills_taught": ["Algorithm Design", "Complexity Analysis", "Greedy Algorithms", "Divide & Conquer", "NP-Completeness"],
        "career_paths": ["Software Engineer", "SDE", "Competitive Programmer"],
        "employability_index": 0.87,
    },
    {
        "id": "ROBOTICS", "name": "Robotics", "credits": 3,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 13, 2026", "seats": 40,
        "tags": ["robotics", "automation", "control systems", "sensors", "kinematics"],
        "department": "Computer Science",
        "skills_taught": ["Kinematics", "Control Systems", "Sensors", "ROS", "Automation"],
        "career_paths": ["Robotics Engineer", "Automation Engineer", "Mechatronics Engineer"],
        "employability_index": 0.76,
    },
    {
        "id": "VISUALPROG", "name": "Visual Programming", "credits": 3,
        "min_cgpa": 5.5, "max_backlog": 2, "last_date": "Aug 16, 2026", "seats": 70,
        "tags": ["visual programming", "gui", "desktop apps", "event driven"],
        "department": "Computer Science",
        "skills_taught": ["GUI Design", "Event-Driven Programming", "C#", ".NET", "Desktop App Development"],
        "career_paths": ["Desktop App Developer", "Software Engineer", "UI Developer"],
        "employability_index": 0.68,
    },
    {
        "id": "NETWORKS", "name": "Computer Networks", "credits": 4,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 12, 2026", "seats": 75,
        "tags": ["computer networks", "networking", "tcp/ip", "protocols"],
        "department": "Computer Science",
        "skills_taught": ["TCP/IP", "Routing", "Network Security Basics", "Protocols", "Subnetting"],
        "career_paths": ["Network Engineer", "Network Administrator", "Security Engineer"],
        "employability_index": 0.75,
    },
    {
        "id": "COMPILERS", "name": "Compiler Design", "credits": 4,
        "min_cgpa": 7.5, "max_backlog": 0, "last_date": "Aug 10, 2026", "seats": 35,
        "tags": ["compiler design", "compilers", "parsing", "lexical analysis"],
        "department": "Computer Science",
        "skills_taught": ["Lexical Analysis", "Parsing", "Syntax Trees", "Code Generation", "Optimization"],
        "career_paths": ["Compiler Engineer", "Language Designer", "Systems Programmer"],
        "employability_index": 0.78,
    },
    {
        "id": "GRAPHICS", "name": "Computer Graphics", "credits": 3,
        "min_cgpa": 6.0, "max_backlog": 2, "last_date": "Aug 15, 2026", "seats": 50,
        "tags": ["computer graphics", "rendering", "3d", "opengl", "animation"],
        "department": "Computer Science",
        "skills_taught": ["OpenGL", "Rendering", "3D Transformations", "Shading", "Animation"],
        "career_paths": ["Graphics Engineer", "Game Developer", "Visualization Engineer"],
        "employability_index": 0.73,
    },

    # ---------------------------------------------------------------- Electronics
    {
        "id": "DIGELEC", "name": "Digital Electronics", "credits": 4,
        "min_cgpa": 6.0, "max_backlog": 2, "last_date": "Aug 14, 2026", "seats": 70,
        "tags": ["digital electronics", "logic gates", "circuits", "electronics"],
        "department": "Electronics",
        "skills_taught": ["Logic Gates", "Boolean Algebra", "Flip-Flops", "Counters", "Digital Circuit Design"],
        "career_paths": ["Electronics Engineer", "Digital Design Engineer", "Hardware Engineer"],
        "employability_index": 0.72,
    },
    {
        "id": "ANALOGELEC", "name": "Analog Electronics", "credits": 4,
        "min_cgpa": 6.0, "max_backlog": 2, "last_date": "Aug 14, 2026", "seats": 65,
        "tags": ["analog electronics", "amplifiers", "circuits", "electronics"],
        "department": "Electronics",
        "skills_taught": ["Diodes", "Transistors", "Amplifiers", "Op-Amps", "Filter Design"],
        "career_paths": ["Electronics Engineer", "Circuit Design Engineer", "Test Engineer"],
        "employability_index": 0.70,
    },
    {
        "id": "EDC", "name": "Electronic Devices & Circuits", "credits": 3,
        "min_cgpa": 5.5, "max_backlog": 2, "last_date": "Aug 16, 2026", "seats": 75,
        "tags": ["electronic devices", "circuits", "semiconductors"],
        "department": "Electronics",
        "skills_taught": ["Semiconductors", "PN Junctions", "Rectifiers", "BJT", "FET"],
        "career_paths": ["Electronics Engineer", "Field Engineer", "Hardware Technician"],
        "employability_index": 0.68,
    },
    {
        "id": "MICROPROC", "name": "Microprocessors & Microcontrollers", "credits": 4,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 12, 2026", "seats": 60,
        "tags": ["microprocessors", "microcontrollers", "embedded", "8051", "arm"],
        "department": "Electronics",
        "skills_taught": ["8051", "ARM", "Assembly Language", "Interfacing", "Embedded C"],
        "career_paths": ["Embedded Engineer", "Firmware Engineer", "Hardware Engineer"],
        "employability_index": 0.78,
    },
    {
        "id": "VLSI", "name": "VLSI Design", "credits": 4,
        "min_cgpa": 7.0, "max_backlog": 1, "last_date": "Aug 11, 2026", "seats": 40,
        "tags": ["vlsi", "chip design", "semiconductor", "asic", "fpga"],
        "department": "Electronics",
        "skills_taught": ["VHDL", "Verilog", "ASIC Design", "FPGA", "Layout Design"],
        "career_paths": ["VLSI Design Engineer", "Chip Designer", "FPGA Engineer"],
        "employability_index": 0.84,
    },
    {
        "id": "SIGSYS", "name": "Signals & Systems", "credits": 4,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 13, 2026", "seats": 65,
        "tags": ["signals", "systems", "fourier", "laplace", "dsp"],
        "department": "Electronics",
        "skills_taught": ["Fourier Transform", "Laplace Transform", "Z-Transform", "Signal Processing", "MATLAB"],
        "career_paths": ["DSP Engineer", "Signal Processing Engineer", "R&D Engineer"],
        "employability_index": 0.74,
    },
    {
        "id": "CONTROLSYS", "name": "Control Systems", "credits": 4,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 13, 2026", "seats": 55,
        "tags": ["control systems", "feedback", "stability", "pid"],
        "department": "Electronics",
        "skills_taught": ["Transfer Functions", "PID Control", "Stability Analysis", "Feedback Systems", "MATLAB/Simulink"],
        "career_paths": ["Control Systems Engineer", "Automation Engineer", "Instrumentation Engineer"],
        "employability_index": 0.75,
    },
    {
        "id": "COMMSYS", "name": "Communication Systems", "credits": 4,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 12, 2026", "seats": 60,
        "tags": ["communication systems", "modulation", "wireless", "signal transmission"],
        "department": "Electronics",
        "skills_taught": ["Modulation Techniques", "Wireless Communication", "Antenna Theory", "Signal Transmission"],
        "career_paths": ["Communications Engineer", "RF Engineer", "Telecom Engineer"],
        "employability_index": 0.76,
    },
    {
        "id": "POWERELEC", "name": "Power Electronics", "credits": 4,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 13, 2026", "seats": 50,
        "tags": ["power electronics", "converters", "inverters", "motor drives"],
        "department": "Electronics",
        "skills_taught": ["Rectifiers", "Inverters", "DC-DC Converters", "Motor Drives", "SCR"],
        "career_paths": ["Power Electronics Engineer", "Energy Systems Engineer", "Field Engineer"],
        "employability_index": 0.73,
    },
    {
        "id": "EMBEDDEDSYS", "name": "Embedded Systems Design", "credits": 4,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 12, 2026", "seats": 55,
        "tags": ["embedded systems", "rtos", "firmware", "hardware"],
        "department": "Electronics",
        "skills_taught": ["RTOS", "Firmware Development", "Hardware-Software Co-design", "Debugging"],
        "career_paths": ["Embedded Systems Engineer", "Firmware Engineer", "IoT Engineer"],
        "employability_index": 0.80,
    },
    {
        "id": "PCBDESIGN", "name": "PCB Design & Fabrication", "credits": 3,
        "min_cgpa": 5.5, "max_backlog": 2, "last_date": "Aug 16, 2026", "seats": 45,
        "tags": ["pcb design", "fabrication", "circuit layout", "eda tools"],
        "department": "Electronics",
        "skills_taught": ["PCB Layout", "Altium", "KiCad", "Gerber Files", "Circuit Fabrication"],
        "career_paths": ["PCB Design Engineer", "Hardware Engineer", "Product Design Engineer"],
        "employability_index": 0.69,
    },
    {
        "id": "EMFT", "name": "Electromagnetic Field Theory", "credits": 4,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 11, 2026", "seats": 50,
        "tags": ["electromagnetics", "field theory", "maxwell equations"],
        "department": "Electronics",
        "skills_taught": ["Maxwell's Equations", "Wave Propagation", "Transmission Lines", "Antenna Basics"],
        "career_paths": ["RF Engineer", "Antenna Design Engineer", "Research Engineer"],
        "employability_index": 0.70,
    },

    # ---------------------------------------------------------------- Mechanical
    {
        "id": "THERMO", "name": "Thermodynamics", "credits": 4,
        "min_cgpa": 6.0, "max_backlog": 2, "last_date": "Aug 14, 2026", "seats": 80,
        "tags": ["thermodynamics", "heat", "energy", "mechanical"],
        "department": "Mechanical",
        "skills_taught": ["Laws of Thermodynamics", "Heat Engines", "Entropy", "Thermodynamic Cycles"],
        "career_paths": ["Mechanical Engineer", "Energy Systems Engineer", "Design Engineer"],
        "employability_index": 0.72,
    },
    {
        "id": "FLUIDMECH", "name": "Fluid Mechanics", "credits": 4,
        "min_cgpa": 6.0, "max_backlog": 2, "last_date": "Aug 14, 2026", "seats": 75,
        "tags": ["fluid mechanics", "hydraulics", "fluid dynamics"],
        "department": "Mechanical",
        "skills_taught": ["Fluid Statics", "Bernoulli's Equation", "Pipe Flow", "Hydraulics"],
        "career_paths": ["Mechanical Engineer", "Hydraulics Engineer", "Design Engineer"],
        "employability_index": 0.70,
    },
    {
        "id": "SOM", "name": "Strength of Materials", "credits": 4,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 12, 2026", "seats": 70,
        "tags": ["strength of materials", "stress", "strain", "beams"],
        "department": "Mechanical",
        "skills_taught": ["Stress-Strain Analysis", "Bending Moments", "Shear Force", "Beam Design"],
        "career_paths": ["Structural Design Engineer", "Mechanical Engineer", "Civil Engineer"],
        "employability_index": 0.73,
    },
    {
        "id": "MACHDESIGN", "name": "Machine Design", "credits": 4,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 13, 2026", "seats": 60,
        "tags": ["machine design", "mechanical components", "gears", "bearings"],
        "department": "Mechanical",
        "skills_taught": ["Gear Design", "Bearing Selection", "Shaft Design", "Fasteners", "AutoCAD"],
        "career_paths": ["Design Engineer", "Product Engineer", "Mechanical Engineer"],
        "employability_index": 0.75,
    },
    {
        "id": "MANUFPROC", "name": "Manufacturing Processes", "credits": 4,
        "min_cgpa": 5.5, "max_backlog": 2, "last_date": "Aug 15, 2026", "seats": 70,
        "tags": ["manufacturing", "casting", "welding", "machining"],
        "department": "Mechanical",
        "skills_taught": ["Casting", "Welding", "Machining", "Forming Processes"],
        "career_paths": ["Production Engineer", "Manufacturing Engineer", "Quality Engineer"],
        "employability_index": 0.71,
    },
    {
        "id": "CADCAM", "name": "CAD/CAM", "credits": 3,
        "min_cgpa": 5.5, "max_backlog": 2, "last_date": "Aug 16, 2026", "seats": 65,
        "tags": ["cad", "cam", "solidworks", "computer aided design"],
        "department": "Mechanical",
        "skills_taught": ["SolidWorks", "AutoCAD", "CNC Programming", "3D Modeling"],
        "career_paths": ["Design Engineer", "CAD Engineer", "Manufacturing Engineer"],
        "employability_index": 0.74,
    },
    {
        "id": "HEATTRANSFER", "name": "Heat Transfer", "credits": 4,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 12, 2026", "seats": 55,
        "tags": ["heat transfer", "conduction", "convection", "radiation"],
        "department": "Mechanical",
        "skills_taught": ["Conduction", "Convection", "Radiation", "Heat Exchangers"],
        "career_paths": ["Thermal Engineer", "HVAC Engineer", "Mechanical Engineer"],
        "employability_index": 0.72,
    },
    {
        "id": "AUTOENG", "name": "Automobile Engineering", "credits": 3,
        "min_cgpa": 5.5, "max_backlog": 2, "last_date": "Aug 16, 2026", "seats": 60,
        "tags": ["automobile", "vehicles", "engines", "transmission"],
        "department": "Mechanical",
        "skills_taught": ["IC Engines", "Transmission Systems", "Vehicle Dynamics", "Braking Systems"],
        "career_paths": ["Automotive Engineer", "Design Engineer", "Test Engineer"],
        "employability_index": 0.71,
    },
    {
        "id": "INDENG", "name": "Industrial Engineering", "credits": 3,
        "min_cgpa": 5.5, "max_backlog": 2, "last_date": "Aug 15, 2026", "seats": 65,
        "tags": ["industrial engineering", "operations", "optimization", "quality"],
        "department": "Mechanical",
        "skills_taught": ["Operations Research", "Quality Control", "Process Optimization", "Lean Manufacturing"],
        "career_paths": ["Industrial Engineer", "Operations Manager", "Process Engineer"],
        "employability_index": 0.73,
    },
    {
        "id": "VIBRATIONS", "name": "Mechanical Vibrations", "credits": 3,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 13, 2026", "seats": 45,
        "tags": ["vibrations", "dynamics", "oscillations"],
        "department": "Mechanical",
        "skills_taught": ["Free Vibrations", "Forced Vibrations", "Damping", "Modal Analysis"],
        "career_paths": ["Mechanical Engineer", "NVH Engineer", "Design Engineer"],
        "employability_index": 0.70,
    },
    {
        "id": "RENEWENERGY", "name": "Renewable Energy Systems", "credits": 3,
        "min_cgpa": 5.5, "max_backlog": 2, "last_date": "Aug 16, 2026", "seats": 60,
        "tags": ["renewable energy", "solar", "wind", "sustainability"],
        "department": "Mechanical",
        "skills_taught": ["Solar Energy Systems", "Wind Energy", "Energy Storage", "Sustainability Analysis"],
        "career_paths": ["Renewable Energy Engineer", "Sustainability Engineer", "Energy Consultant"],
        "employability_index": 0.77,
    },
    {
        "id": "MECHATRONICS", "name": "Mechatronics", "credits": 4,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 12, 2026", "seats": 50,
        "tags": ["mechatronics", "automation", "robotics", "mechanical electronics"],
        "department": "Mechanical",
        "skills_taught": ["Sensors & Actuators", "PLC Programming", "Automation Systems", "Robotics Basics"],
        "career_paths": ["Mechatronics Engineer", "Automation Engineer", "Robotics Engineer"],
        "employability_index": 0.79,
    },

    # ---------------------------------------------------------------- Civil
    {
        "id": "STRUCTENG", "name": "Structural Engineering", "credits": 4,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 12, 2026", "seats": 60,
        "tags": ["structural engineering", "structures", "load analysis"],
        "department": "Civil",
        "skills_taught": ["Structural Analysis", "Load Calculations", "Design Codes", "STAAD Pro"],
        "career_paths": ["Structural Engineer", "Design Engineer", "Site Engineer"],
        "employability_index": 0.74,
    },
    {
        "id": "GEOTECH", "name": "Geotechnical Engineering", "credits": 4,
        "min_cgpa": 6.0, "max_backlog": 2, "last_date": "Aug 14, 2026", "seats": 55,
        "tags": ["geotechnical", "soil mechanics", "foundations"],
        "department": "Civil",
        "skills_taught": ["Soil Mechanics", "Foundation Design", "Slope Stability", "Site Investigation"],
        "career_paths": ["Geotechnical Engineer", "Foundation Engineer", "Site Engineer"],
        "employability_index": 0.72,
    },
    {
        "id": "SURVEYING", "name": "Surveying", "credits": 3,
        "min_cgpa": 5.0, "max_backlog": 3, "last_date": "Aug 18, 2026", "seats": 80,
        "tags": ["surveying", "land measurement", "gis", "total station"],
        "department": "Civil",
        "skills_taught": ["Total Station", "GPS Surveying", "GIS", "Leveling", "Land Measurement"],
        "career_paths": ["Surveyor", "Site Engineer", "GIS Analyst"],
        "employability_index": 0.68,
    },
    {
        "id": "BUILDMAT", "name": "Building Materials & Construction", "credits": 3,
        "min_cgpa": 5.0, "max_backlog": 3, "last_date": "Aug 18, 2026", "seats": 75,
        "tags": ["building materials", "construction", "cement", "bricks"],
        "department": "Civil",
        "skills_taught": ["Cement & Concrete", "Bricks & Blocks", "Construction Techniques", "Material Testing"],
        "career_paths": ["Site Engineer", "Construction Manager", "Quality Engineer"],
        "employability_index": 0.69,
    },
    {
        "id": "TRANSPORTENG", "name": "Transportation Engineering", "credits": 4,
        "min_cgpa": 6.0, "max_backlog": 2, "last_date": "Aug 14, 2026", "seats": 50,
        "tags": ["transportation", "highway engineering", "traffic"],
        "department": "Civil",
        "skills_taught": ["Highway Design", "Traffic Engineering", "Pavement Design", "Transportation Planning"],
        "career_paths": ["Transportation Engineer", "Highway Engineer", "Traffic Planner"],
        "employability_index": 0.71,
    },
    {
        "id": "ENVENG", "name": "Environmental Engineering", "credits": 3,
        "min_cgpa": 5.5, "max_backlog": 2, "last_date": "Aug 16, 2026", "seats": 60,
        "tags": ["environmental engineering", "water treatment", "waste management"],
        "department": "Civil",
        "skills_taught": ["Water Treatment", "Waste Management", "Air Pollution Control", "Environmental Impact Assessment"],
        "career_paths": ["Environmental Engineer", "Sustainability Consultant", "Public Health Engineer"],
        "employability_index": 0.72,
    },
    {
        "id": "CONCRETETECH", "name": "Concrete Technology", "credits": 3,
        "min_cgpa": 5.5, "max_backlog": 2, "last_date": "Aug 16, 2026", "seats": 55,
        "tags": ["concrete technology", "concrete design", "materials"],
        "department": "Civil",
        "skills_taught": ["Concrete Mix Design", "Quality Testing", "Admixtures", "Durability Analysis"],
        "career_paths": ["Materials Engineer", "Quality Control Engineer", "Site Engineer"],
        "employability_index": 0.70,
    },
    {
        "id": "WATERRESOURCE", "name": "Water Resources Engineering", "credits": 4,
        "min_cgpa": 6.0, "max_backlog": 2, "last_date": "Aug 14, 2026", "seats": 45,
        "tags": ["water resources", "hydrology", "irrigation"],
        "department": "Civil",
        "skills_taught": ["Hydrology", "Irrigation Design", "Dam Engineering", "Watershed Management"],
        "career_paths": ["Water Resources Engineer", "Hydrologist", "Irrigation Engineer"],
        "employability_index": 0.71,
    },
    {
        "id": "CONSTRUCTMGMT", "name": "Construction Management", "credits": 3,
        "min_cgpa": 5.5, "max_backlog": 2, "last_date": "Aug 16, 2026", "seats": 65,
        "tags": ["construction management", "project management", "scheduling"],
        "department": "Civil",
        "skills_taught": ["Project Scheduling", "Cost Estimation", "Resource Planning", "MS Project"],
        "career_paths": ["Construction Manager", "Project Manager", "Site Supervisor"],
        "employability_index": 0.73,
    },
    {
        "id": "STEELDESIGN", "name": "Steel Structure Design", "credits": 4,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 12, 2026", "seats": 40,
        "tags": ["steel structures", "structural design", "steel design"],
        "department": "Civil",
        "skills_taught": ["Steel Design Codes", "Connection Design", "Truss Analysis", "STAAD Pro"],
        "career_paths": ["Structural Engineer", "Steel Design Engineer", "Design Consultant"],
        "employability_index": 0.73,
    },
    {
        "id": "EARTHQUAKEENG", "name": "Earthquake Engineering", "credits": 3,
        "min_cgpa": 7.0, "max_backlog": 1, "last_date": "Aug 11, 2026", "seats": 35,
        "tags": ["earthquake engineering", "seismic design", "structural safety"],
        "department": "Civil",
        "skills_taught": ["Seismic Analysis", "Earthquake-Resistant Design", "Base Isolation", "Structural Safety"],
        "career_paths": ["Structural Engineer", "Seismic Design Engineer", "Research Engineer"],
        "employability_index": 0.72,
    },
    {
        "id": "URBANPLAN", "name": "Urban Planning", "credits": 3,
        "min_cgpa": 5.0, "max_backlog": 3, "last_date": "Aug 18, 2026", "seats": 55,
        "tags": ["urban planning", "city planning", "land use"],
        "department": "Civil",
        "skills_taught": ["Land Use Planning", "Zoning", "GIS Mapping", "Sustainable Urban Design"],
        "career_paths": ["Urban Planner", "City Planner", "GIS Analyst"],
        "employability_index": 0.68,
    },

    # ---------------------------------------------------------------- Information Technology
    {
        "id": "ISM", "name": "Information Systems Management", "credits": 3,
        "min_cgpa": 5.5, "max_backlog": 2, "last_date": "Aug 16, 2026", "seats": 70,
        "tags": ["information systems", "it management", "systems analysis"],
        "department": "Information Technology",
        "skills_taught": ["Systems Analysis", "IT Governance", "Business Process Modeling", "ERP Basics"],
        "career_paths": ["IT Manager", "Systems Analyst", "Business Analyst"],
        "employability_index": 0.73,
    },
    {
        "id": "NETADMIN", "name": "Network Administration", "credits": 3,
        "min_cgpa": 5.5, "max_backlog": 2, "last_date": "Aug 15, 2026", "seats": 65,
        "tags": ["network administration", "system administration", "windows server", "linux"],
        "department": "Information Technology",
        "skills_taught": ["Windows Server", "Linux Administration", "Active Directory", "DNS/DHCP"],
        "career_paths": ["Network Administrator", "System Administrator", "IT Support Engineer"],
        "employability_index": 0.72,
    },
    {
        "id": "ITINFRA", "name": "IT Infrastructure & Cloud Services", "credits": 3,
        "min_cgpa": 6.0, "max_backlog": 2, "last_date": "Aug 15, 2026", "seats": 60,
        "tags": ["it infrastructure", "cloud services", "virtualization"],
        "department": "Information Technology",
        "skills_taught": ["Virtualization", "Cloud Fundamentals", "Data Center Operations", "IT Service Management"],
        "career_paths": ["Infrastructure Engineer", "Cloud Support Engineer", "IT Operations Analyst"],
        "employability_index": 0.76,
    },
    {
        "id": "DIGFORENSICS", "name": "Digital Forensics", "credits": 3,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 13, 2026", "seats": 40,
        "tags": ["digital forensics", "cybercrime", "incident response"],
        "department": "Information Technology",
        "skills_taught": ["Evidence Collection", "Incident Response", "Forensic Tools", "Chain of Custody"],
        "career_paths": ["Digital Forensics Analyst", "Cybercrime Investigator", "Security Analyst"],
        "employability_index": 0.77,
    },
    {
        "id": "ERP", "name": "Enterprise Resource Planning", "credits": 3,
        "min_cgpa": 5.5, "max_backlog": 2, "last_date": "Aug 16, 2026", "seats": 55,
        "tags": ["erp", "sap", "enterprise systems"],
        "department": "Information Technology",
        "skills_taught": ["SAP Basics", "ERP Modules", "Business Process Integration", "Change Management"],
        "career_paths": ["ERP Consultant", "Functional Analyst", "IT Business Analyst"],
        "employability_index": 0.71,
    },
    {
        "id": "ITPM", "name": "IT Project Management", "credits": 3,
        "min_cgpa": 6.0, "max_backlog": 2, "last_date": "Aug 15, 2026", "seats": 60,
        "tags": ["it project management", "agile", "scrum", "pmp"],
        "department": "Information Technology",
        "skills_taught": ["Agile", "Scrum", "Risk Management", "Project Scheduling", "Jira"],
        "career_paths": ["IT Project Manager", "Scrum Master", "Delivery Manager"],
        "employability_index": 0.78,
    },
    {
        "id": "INFOSECMGMT", "name": "Information Security Management", "credits": 3,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 13, 2026", "seats": 50,
        "tags": ["information security", "security management", "compliance", "risk"],
        "department": "Information Technology",
        "skills_taught": ["Security Policies", "Risk Assessment", "Compliance (ISO 27001)", "Security Auditing"],
        "career_paths": ["Security Manager", "Compliance Analyst", "IT Auditor"],
        "employability_index": 0.79,
    },
    {
        "id": "BIA", "name": "Business Intelligence & Analytics", "credits": 3,
        "min_cgpa": 6.0, "max_backlog": 2, "last_date": "Aug 15, 2026", "seats": 65,
        "tags": ["business intelligence", "bi", "analytics", "dashboards"],
        "department": "Information Technology",
        "skills_taught": ["Power BI", "Data Warehousing Basics", "KPI Dashboards", "SQL"],
        "career_paths": ["BI Analyst", "BI Developer", "Data Analyst"],
        "employability_index": 0.77,
    },
    {
        "id": "MOBCOMPUTING", "name": "Mobile Computing", "credits": 3,
        "min_cgpa": 5.5, "max_backlog": 2, "last_date": "Aug 16, 2026", "seats": 55,
        "tags": ["mobile computing", "wireless networks", "mobile platforms"],
        "department": "Information Technology",
        "skills_taught": ["Wireless Protocols", "Mobile OS Fundamentals", "Mobile App Architecture", "GPS/Location Services"],
        "career_paths": ["Mobile Systems Engineer", "Wireless Engineer", "Mobile App Developer"],
        "employability_index": 0.74,
    },
    {
        "id": "HCI", "name": "Human-Computer Interaction", "credits": 3,
        "min_cgpa": 5.5, "max_backlog": 2, "last_date": "Aug 16, 2026", "seats": 60,
        "tags": ["hci", "human computer interaction", "usability", "ux research"],
        "department": "Information Technology",
        "skills_taught": ["Usability Testing", "Interaction Design", "User Research", "Prototyping"],
        "career_paths": ["UX Researcher", "Interaction Designer", "Product Designer"],
        "employability_index": 0.73,
    },
    {
        "id": "ECOMMERCE", "name": "E-Commerce Technologies", "credits": 3,
        "min_cgpa": 5.0, "max_backlog": 3, "last_date": "Aug 18, 2026", "seats": 70,
        "tags": ["e-commerce", "online payments", "web technologies"],
        "department": "Information Technology",
        "skills_taught": ["Payment Gateways", "E-Commerce Platforms", "Digital Marketing Basics", "Web Security"],
        "career_paths": ["E-Commerce Developer", "Digital Business Analyst", "Web Developer"],
        "employability_index": 0.72,
    },
    {
        "id": "WEBTECH", "name": "Web Technologies", "credits": 3,
        "min_cgpa": 5.0, "max_backlog": 3, "last_date": "Aug 18, 2026", "seats": 80,
        "tags": ["web technologies", "html", "css", "javascript", "web protocols"],
        "department": "Information Technology",
        "skills_taught": ["HTML/CSS", "JavaScript", "HTTP/HTTPS", "Web Hosting Basics"],
        "career_paths": ["Web Developer", "IT Support Engineer", "Web Administrator"],
        "employability_index": 0.70,
    },
]

COURSE_BY_ID = {c["id"]: c for c in COURSES}

DEPARTMENTS = [
    "Computer Science",
    "Artificial Intelligence and Machine Learning",
    "Data Science",
    "Information Technology",
    "Electronics",
    "Mechanical",
    "Civil",
]

# Skills a working professional is generally expected to have in each
# career path -- used for skill-gap analysis and resume matching.
CAREER_REQUIRED_SKILLS = {
    "AIML":       ["Python", "Machine Learning", "Deep Learning", "Statistics", "SQL", "Neural Networks"],
    "DS":         ["Python", "SQL", "Statistics", "Data Visualization", "Excel", "Pandas"],
    "WEB":        ["HTML", "CSS", "JavaScript", "React", "Node.js", "Git", "REST APIs"],
    "CYB":        ["Network Security", "Linux", "Cryptography", "Ethical Hacking", "Risk Analysis", "Python"],
    "CLOUD":      ["AWS", "Docker", "Kubernetes", "Linux", "CI/CD", "Python"],
    "FULLSTACK":  ["React", "Node.js", "JavaScript", "MongoDB", "REST APIs", "Git", "SQL"],
    "BACKEND":    ["Python", "Java", "SQL", "REST APIs", "System Design", "Git"],
    "DEVOPS":     ["Docker", "Kubernetes", "CI/CD", "Terraform", "Linux", "Jenkins"],
    "ANALYTICS":  ["Excel", "SQL", "Power BI", "Tableau", "Statistics"],
    "MOBILE":     ["Flutter", "React Native", "Kotlin", "REST APIs", "Git"],
    "UIUX":       ["Figma", "Wireframing", "Prototyping", "User Research"],
    "BLOCKCHAIN": ["Solidity", "Smart Contracts", "Ethereum", "Web3.js", "Cryptography"],
    "PHYSICS":    ["Classical Mechanics", "Electromagnetism", "Thermodynamics"],
    "MATHS":      ["Calculus", "Linear Algebra", "Probability", "Discrete Mathematics"],
    "CPROG":      ["C", "Pointers", "Memory Management", "Debugging"],
    "CPP":        ["C++", "OOP", "STL", "Data Structures"],
    "JAVA":       ["Java", "OOP", "Spring Boot", "JVM"],
    "PYTHON":     ["Python", "OOP", "Scripting", "Automation"],
    "DSA":        ["Arrays", "Trees", "Graphs", "Dynamic Programming", "Algorithm Design"],
    "FLASK":      ["Flask", "Python", "REST APIs", "SQLAlchemy", "Jinja2"],
    "FRONTEND":   ["HTML", "CSS", "JavaScript", "React", "Responsive Design"],
    "SQL":        ["SQL", "Joins", "Indexing", "Query Optimization"],
    "OOP":        ["OOP", "Design Patterns", "Encapsulation", "Inheritance", "Polymorphism"],
    "DBMS":       ["DBMS", "Normalization", "SQL", "Transactions", "Indexing"],
    "SWE":        ["SDLC", "Agile", "Testing", "Requirements Analysis", "UML"],
    "SYSDESIGN":  ["System Design", "Scalability", "Load Balancing", "Distributed Systems", "Caching"],
    "DOCKER":     ["Docker", "Containerization", "Docker Compose", "Images"],
    "FASTAPI":    ["FastAPI", "Python", "Async Programming", "REST APIs", "Pydantic"],
    "GENAI":      ["LLMs", "Prompt Engineering", "Transformers", "Fine-tuning", "RAG"],
    "ML":         ["Python", "Supervised Learning", "Unsupervised Learning", "Model Evaluation", "Scikit-learn"],
    "DATAANALYTICS": ["Excel", "SQL", "Statistics", "Data Visualization", "Python"],
    "IOT":        ["Embedded C", "Sensors", "Microcontrollers", "MQTT", "Edge Computing"],
    "DWDM":       ["ETL", "OLAP", "Data Mining", "Clustering", "Association Rules"],
    "OS":         ["Process Scheduling", "Memory Management", "Concurrency", "File Systems", "Threads"],
    "ACA":        ["Pipelining", "Cache Optimization", "Parallel Computing", "Instruction Sets"],
    "DAA":        ["Algorithm Design", "Complexity Analysis", "Greedy Algorithms", "Divide & Conquer", "NP-Completeness"],
    "ROBOTICS":   ["Kinematics", "Control Systems", "Sensors", "ROS", "Automation"],
    "VISUALPROG": ["GUI Design", "Event-Driven Programming", "C#", ".NET", "Desktop App Development"],
    "NETWORKS":   ["TCP/IP", "Routing", "Network Security Basics", "Protocols", "Subnetting"],
    "COMPILERS":  ["Lexical Analysis", "Parsing", "Syntax Trees", "Code Generation", "Optimization"],
    "GRAPHICS":   ["OpenGL", "Rendering", "3D Transformations", "Shading", "Animation"],

    # Electronics
    "DIGELEC":     ["Logic Gates", "Boolean Algebra", "Flip-Flops", "Counters"],
    "ANALOGELEC":  ["Diodes", "Transistors", "Amplifiers", "Op-Amps"],
    "EDC":         ["Semiconductors", "PN Junctions", "Rectifiers", "BJT"],
    "MICROPROC":   ["8051", "ARM", "Assembly Language", "Embedded C"],
    "VLSI":        ["VHDL", "Verilog", "ASIC Design", "FPGA"],
    "SIGSYS":      ["Fourier Transform", "Laplace Transform", "Signal Processing", "MATLAB"],
    "CONTROLSYS":  ["Transfer Functions", "PID Control", "Stability Analysis", "MATLAB/Simulink"],
    "COMMSYS":     ["Modulation Techniques", "Wireless Communication", "Antenna Theory"],
    "POWERELEC":   ["Rectifiers", "Inverters", "DC-DC Converters", "Motor Drives"],
    "EMBEDDEDSYS": ["RTOS", "Firmware Development", "Hardware-Software Co-design"],
    "PCBDESIGN":   ["PCB Layout", "Altium", "KiCad", "Circuit Fabrication"],
    "EMFT":        ["Maxwell's Equations", "Wave Propagation", "Transmission Lines"],

    # Mechanical
    "THERMO":        ["Laws of Thermodynamics", "Heat Engines", "Entropy"],
    "FLUIDMECH":     ["Fluid Statics", "Bernoulli's Equation", "Pipe Flow"],
    "SOM":           ["Stress-Strain Analysis", "Bending Moments", "Beam Design"],
    "MACHDESIGN":    ["Gear Design", "Bearing Selection", "Shaft Design", "AutoCAD"],
    "MANUFPROC":     ["Casting", "Welding", "Machining", "Forming Processes"],
    "CADCAM":        ["SolidWorks", "AutoCAD", "CNC Programming", "3D Modeling"],
    "HEATTRANSFER":  ["Conduction", "Convection", "Radiation", "Heat Exchangers"],
    "AUTOENG":       ["IC Engines", "Transmission Systems", "Vehicle Dynamics"],
    "INDENG":        ["Operations Research", "Quality Control", "Process Optimization"],
    "VIBRATIONS":    ["Free Vibrations", "Forced Vibrations", "Damping", "Modal Analysis"],
    "RENEWENERGY":   ["Solar Energy Systems", "Wind Energy", "Energy Storage"],
    "MECHATRONICS":  ["Sensors & Actuators", "PLC Programming", "Automation Systems"],

    # Civil
    "STRUCTENG":     ["Structural Analysis", "Load Calculations", "STAAD Pro"],
    "GEOTECH":       ["Soil Mechanics", "Foundation Design", "Slope Stability"],
    "SURVEYING":     ["Total Station", "GPS Surveying", "GIS", "Leveling"],
    "BUILDMAT":      ["Cement & Concrete", "Bricks & Blocks", "Material Testing"],
    "TRANSPORTENG":  ["Highway Design", "Traffic Engineering", "Pavement Design"],
    "ENVENG":        ["Water Treatment", "Waste Management", "Air Pollution Control"],
    "CONCRETETECH":  ["Concrete Mix Design", "Quality Testing", "Admixtures"],
    "WATERRESOURCE": ["Hydrology", "Irrigation Design", "Dam Engineering"],
    "CONSTRUCTMGMT": ["Project Scheduling", "Cost Estimation", "MS Project"],
    "STEELDESIGN":   ["Steel Design Codes", "Connection Design", "STAAD Pro"],
    "EARTHQUAKEENG": ["Seismic Analysis", "Earthquake-Resistant Design", "Base Isolation"],
    "URBANPLAN":     ["Land Use Planning", "Zoning", "GIS Mapping"],

    # Information Technology
    "ISM":           ["Systems Analysis", "IT Governance", "Business Process Modeling"],
    "NETADMIN":      ["Windows Server", "Linux Administration", "Active Directory"],
    "ITINFRA":       ["Virtualization", "Cloud Fundamentals", "IT Service Management"],
    "DIGFORENSICS":  ["Evidence Collection", "Incident Response", "Forensic Tools"],
    "ERP":           ["SAP Basics", "ERP Modules", "Business Process Integration"],
    "ITPM":          ["Agile", "Scrum", "Risk Management", "Jira"],
    "INFOSECMGMT":   ["Security Policies", "Risk Assessment", "Security Auditing"],
    "BIA":           ["Power BI", "Data Warehousing Basics", "KPI Dashboards", "SQL"],
    "MOBCOMPUTING":  ["Wireless Protocols", "Mobile OS Fundamentals", "Mobile App Architecture"],
    "HCI":           ["Usability Testing", "Interaction Design", "User Research"],
    "ECOMMERCE":     ["Payment Gateways", "E-Commerce Platforms", "Web Security"],
    "WEBTECH":       ["HTML/CSS", "JavaScript", "HTTP/HTTPS"],
}

# Master skill vocabulary the resume analyzer scans for.
ALL_KNOWN_SKILLS = sorted(set(
    skill for skills in CAREER_REQUIRED_SKILLS.values() for skill in skills
) | {
    "Java", "C++", "TensorFlow", "PyTorch", "Django", "Flask", "MongoDB", "Excel",
    "Git", "Tableau", "Power BI", "Terraform", "Jenkins", "Kotlin", "Swift",
    "Figma", "Solidity", "GraphQL", "Redis", "PostgreSQL",
    "AutoCAD", "SolidWorks", "MATLAB", "STAAD Pro", "Altium", "KiCad",
})