"""
Central course catalog. The Flask API, the ML training scripts, the
recommendation engine, career roadmaps, skill-gap analysis, interview
prep and placement model all import this so every feature stays in sync
with a single source of truth.
"""

COURSES = [
    {
        "id": "AIML", "name": "AI & Machine Learning", "credits": 4,
        "min_cgpa": 7.5, "max_backlog": 0, "last_date": "Aug 10, 2026", "seats": 60,
        "tags": ["ai", "machine learning", "neural networks", "python", "deep learning", "data"],
        "skills_taught": ["Python", "Machine Learning", "Deep Learning", "Neural Networks", "Statistics"],
        "career_paths": ["ML Engineer", "AI Researcher", "Data Scientist"],
        "employability_index": 0.90,
    },
    {
        "id": "DS", "name": "Data Science", "credits": 4,
        "min_cgpa": 7.0, "max_backlog": 1, "last_date": "Aug 10, 2026", "seats": 60,
        "tags": ["data", "analytics", "statistics", "python", "visualization", "sql"],
        "skills_taught": ["Python", "SQL", "Statistics", "Data Visualization", "Pandas"],
        "career_paths": ["Data Analyst", "Data Scientist", "BI Analyst"],
        "employability_index": 0.85,
    },
    {
        "id": "WEB", "name": "Web Development", "credits": 3,
        "min_cgpa": 6.0, "max_backlog": 2, "last_date": "Aug 15, 2026", "seats": 80,
        "tags": ["web", "frontend", "backend", "javascript", "react", "html", "css"],
        "skills_taught": ["HTML", "CSS", "JavaScript", "React", "Node.js", "REST APIs"],
        "career_paths": ["Frontend Developer", "Full-Stack Developer", "Web Engineer"],
        "employability_index": 0.78,
    },
    {
        "id": "CYB", "name": "Cyber Security", "credits": 4,
        "min_cgpa": 7.0, "max_backlog": 1, "last_date": "Aug 12, 2026", "seats": 50,
        "tags": ["security", "networking", "ethical hacking", "cryptography", "linux"],
        "skills_taught": ["Network Security", "Cryptography", "Ethical Hacking", "Linux", "Risk Analysis"],
        "career_paths": ["Security Analyst", "Penetration Tester", "SOC Engineer"],
        "employability_index": 0.83,
    },
    {
        "id": "CLOUD", "name": "Cloud Computing", "credits": 3,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 12, 2026", "seats": 55,
        "tags": ["cloud", "aws", "azure", "devops", "docker", "kubernetes", "infrastructure"],
        "skills_taught": ["AWS", "Docker", "Kubernetes", "CI/CD", "Linux"],
        "career_paths": ["Cloud Engineer", "DevOps Engineer", "Site Reliability Engineer"],
        "employability_index": 0.87,
    },
    {
        "id": "FULLSTACK", "name": "Full Stack Development", "credits": 4,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 14, 2026", "seats": 70,
        "tags": ["fullstack", "frontend", "backend", "javascript", "react", "node", "database", "api"],
        "skills_taught": ["React", "Node.js", "Express", "MongoDB", "REST APIs", "Git"],
        "career_paths": ["Full-Stack Developer", "Software Engineer", "Product Engineer"],
        "employability_index": 0.88,
    },
    {
        "id": "BACKEND", "name": "Backend Development", "credits": 4,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 14, 2026", "seats": 60,
        "tags": ["backend", "server", "api", "database", "python", "java", "microservices"],
        "skills_taught": ["Python", "Java", "SQL", "REST APIs", "System Design", "Microservices"],
        "career_paths": ["Backend Developer", "API Engineer", "Software Engineer"],
        "employability_index": 0.86,
    },
    {
        "id": "DEVOPS", "name": "DevOps Engineering", "credits": 4,
        "min_cgpa": 7.0, "max_backlog": 1, "last_date": "Aug 13, 2026", "seats": 45,
        "tags": ["devops", "ci/cd", "docker", "kubernetes", "automation", "infrastructure", "linux"],
        "skills_taught": ["Docker", "Kubernetes", "CI/CD", "Terraform", "Linux", "Jenkins"],
        "career_paths": ["DevOps Engineer", "Site Reliability Engineer", "Platform Engineer"],
        "employability_index": 0.89,
    },
    {
        "id": "ANALYTICS", "name": "Data & Business Analytics", "credits": 3,
        "min_cgpa": 6.0, "max_backlog": 2, "last_date": "Aug 16, 2026", "seats": 75,
        "tags": ["analytics", "business intelligence", "excel", "sql", "dashboards", "statistics", "data"],
        "skills_taught": ["Excel", "SQL", "Power BI", "Tableau", "Statistics", "Data Storytelling"],
        "career_paths": ["Business Analyst", "Data Analyst", "BI Developer"],
        "employability_index": 0.80,
    },
    {
        "id": "MOBILE", "name": "Mobile App Development", "credits": 3,
        "min_cgpa": 6.0, "max_backlog": 2, "last_date": "Aug 15, 2026", "seats": 55,
        "tags": ["mobile", "android", "ios", "flutter", "react native", "app"],
        "skills_taught": ["Flutter", "React Native", "Kotlin", "REST APIs", "UI Design"],
        "career_paths": ["Mobile Developer", "Android Engineer", "iOS Engineer"],
        "employability_index": 0.79,
    },
    {
        "id": "UIUX", "name": "UI/UX Design", "credits": 3,
        "min_cgpa": 5.5, "max_backlog": 2, "last_date": "Aug 16, 2026", "seats": 50,
        "tags": ["design", "ui", "ux", "figma", "prototyping", "user research"],
        "skills_taught": ["Figma", "Wireframing", "Prototyping", "User Research", "Design Systems"],
        "career_paths": ["UI Designer", "UX Designer", "Product Designer"],
        "employability_index": 0.75,
    },
    {
        "id": "BLOCKCHAIN", "name": "Blockchain & Web3", "credits": 3,
        "min_cgpa": 7.0, "max_backlog": 1, "last_date": "Aug 13, 2026", "seats": 35,
        "tags": ["blockchain", "web3", "solidity", "smart contracts", "crypto", "ethereum"],
        "skills_taught": ["Solidity", "Smart Contracts", "Ethereum", "Web3.js", "Cryptography"],
        "career_paths": ["Blockchain Developer", "Smart Contract Engineer", "Web3 Engineer"],
        "employability_index": 0.76,
    },
    {
        "id": "PHYSICS", "name": "Applied Physics", "credits": 3,
        "min_cgpa": 5.0, "max_backlog": 3, "last_date": "Aug 18, 2026", "seats": 100,
        "tags": ["physics", "mechanics", "electromagnetism", "thermodynamics", "science", "core"],
        "skills_taught": ["Classical Mechanics", "Electromagnetism", "Thermodynamics", "Problem Solving"],
        "career_paths": ["Research Assistant", "R&D Engineer", "Physics Educator"],
        "employability_index": 0.55,
    },
    {
        "id": "MATHS", "name": "Engineering Mathematics", "credits": 3,
        "min_cgpa": 5.0, "max_backlog": 3, "last_date": "Aug 18, 2026", "seats": 100,
        "tags": ["mathematics", "maths", "calculus", "algebra", "statistics", "core"],
        "skills_taught": ["Calculus", "Linear Algebra", "Probability", "Discrete Mathematics"],
        "career_paths": ["Quantitative Analyst", "Data Scientist", "Research Assistant"],
        "employability_index": 0.62,
    },
    {
        "id": "CPROG", "name": "C Programming", "credits": 3,
        "min_cgpa": 5.0, "max_backlog": 3, "last_date": "Aug 17, 2026", "seats": 90,
        "tags": ["c", "programming", "fundamentals", "systems", "memory"],
        "skills_taught": ["C", "Pointers", "Memory Management", "Debugging"],
        "career_paths": ["Systems Programmer", "Embedded Engineer", "Software Engineer"],
        "employability_index": 0.65,
    },
    {
        "id": "CPP", "name": "C++ Programming", "credits": 3,
        "min_cgpa": 5.5, "max_backlog": 2, "last_date": "Aug 17, 2026", "seats": 80,
        "tags": ["c++", "cpp", "oop", "programming", "systems", "competitive programming"],
        "skills_taught": ["C++", "OOP", "STL", "Data Structures"],
        "career_paths": ["Software Engineer", "Game Developer", "Competitive Programmer"],
        "employability_index": 0.72,
    },
    {
        "id": "JAVA", "name": "Java Programming", "credits": 3,
        "min_cgpa": 5.5, "max_backlog": 2, "last_date": "Aug 17, 2026", "seats": 85,
        "tags": ["java", "oop", "backend", "enterprise", "android"],
        "skills_taught": ["Java", "OOP", "Spring Boot", "JVM"],
        "career_paths": ["Java Developer", "Backend Engineer", "Android Developer"],
        "employability_index": 0.75,
    },
    {
        "id": "PYTHON", "name": "Python Programming", "credits": 3,
        "min_cgpa": 5.0, "max_backlog": 3, "last_date": "Aug 17, 2026", "seats": 100,
        "tags": ["python", "programming", "scripting", "automation", "fundamentals"],
        "skills_taught": ["Python", "OOP", "Scripting", "Automation"],
        "career_paths": ["Python Developer", "Automation Engineer", "Software Engineer"],
        "employability_index": 0.78,
    },
    {
        "id": "DSA", "name": "Data Structures & Algorithms", "credits": 4,
        "min_cgpa": 7.0, "max_backlog": 1, "last_date": "Aug 11, 2026", "seats": 70,
        "tags": ["dsa", "algorithms", "data structures", "competitive programming", "problem solving"],
        "skills_taught": ["Arrays", "Trees", "Graphs", "Dynamic Programming", "Algorithm Design"],
        "career_paths": ["Software Engineer", "SDE", "Competitive Programmer"],
        "employability_index": 0.88,
    },
    {
        "id": "FLASK", "name": "Flask Web Development", "credits": 3,
        "min_cgpa": 6.0, "max_backlog": 2, "last_date": "Aug 15, 2026", "seats": 60,
        "tags": ["flask", "python", "backend", "web", "api"],
        "skills_taught": ["Flask", "Python", "REST APIs", "SQLAlchemy", "Jinja2"],
        "career_paths": ["Backend Developer", "Python Web Developer", "API Engineer"],
        "employability_index": 0.76,
    },
    {
        "id": "FRONTEND", "name": "Frontend Development", "credits": 3,
        "min_cgpa": 5.5, "max_backlog": 2, "last_date": "Aug 16, 2026", "seats": 85,
        "tags": ["frontend", "react", "javascript", "html", "css", "ui"],
        "skills_taught": ["HTML", "CSS", "JavaScript", "React", "Responsive Design"],
        "career_paths": ["Frontend Developer", "UI Engineer", "Web Developer"],
        "employability_index": 0.77,
    },
    {
        "id": "SQL", "name": "SQL & Database Querying", "credits": 2,
        "min_cgpa": 5.0, "max_backlog": 3, "last_date": "Aug 18, 2026", "seats": 100,
        "tags": ["sql", "database", "query", "data"],
        "skills_taught": ["SQL", "Joins", "Indexing", "Query Optimization"],
        "career_paths": ["Database Developer", "Data Analyst", "Backend Developer"],
        "employability_index": 0.70,
    },
    {
        "id": "OOP", "name": "Object-Oriented Programming", "credits": 3,
        "min_cgpa": 5.5, "max_backlog": 2, "last_date": "Aug 17, 2026", "seats": 90,
        "tags": ["oop", "programming", "design patterns", "java", "c++"],
        "skills_taught": ["OOP", "Design Patterns", "Encapsulation", "Inheritance", "Polymorphism"],
        "career_paths": ["Software Engineer", "Application Developer"],
        "employability_index": 0.72,
    },
    {
        "id": "DBMS", "name": "Database Management Systems", "credits": 3,
        "min_cgpa": 6.0, "max_backlog": 2, "last_date": "Aug 16, 2026", "seats": 85,
        "tags": ["dbms", "database", "sql", "normalization", "transactions"],
        "skills_taught": ["DBMS", "Normalization", "SQL", "Transactions", "Indexing"],
        "career_paths": ["Database Administrator", "Backend Developer", "Data Engineer"],
        "employability_index": 0.74,
    },
    {
        "id": "SWE", "name": "Software Engineering", "credits": 3,
        "min_cgpa": 6.0, "max_backlog": 2, "last_date": "Aug 16, 2026", "seats": 90,
        "tags": ["software engineering", "sdlc", "agile", "testing", "design"],
        "skills_taught": ["SDLC", "Agile", "Testing", "Requirements Analysis", "UML"],
        "career_paths": ["Software Engineer", "QA Engineer", "Product Engineer"],
        "employability_index": 0.80,
    },
    {
        "id": "SYSDESIGN", "name": "System Design", "credits": 4,
        "min_cgpa": 7.5, "max_backlog": 0, "last_date": "Aug 11, 2026", "seats": 50,
        "tags": ["system design", "scalability", "architecture", "distributed systems"],
        "skills_taught": ["System Design", "Scalability", "Load Balancing", "Distributed Systems", "Caching"],
        "career_paths": ["Software Architect", "Senior SDE", "Backend Engineer"],
        "employability_index": 0.91,
    },
    {
        "id": "DOCKER", "name": "Docker & Containerization", "credits": 2,
        "min_cgpa": 6.0, "max_backlog": 2, "last_date": "Aug 15, 2026", "seats": 65,
        "tags": ["docker", "containers", "devops", "kubernetes"],
        "skills_taught": ["Docker", "Containerization", "Docker Compose", "Images"],
        "career_paths": ["DevOps Engineer", "Cloud Engineer", "Backend Developer"],
        "employability_index": 0.79,
    },
    {
        "id": "FASTAPI", "name": "FastAPI Web Development", "credits": 3,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 14, 2026", "seats": 55,
        "tags": ["fastapi", "python", "backend", "api", "async"],
        "skills_taught": ["FastAPI", "Python", "Async Programming", "REST APIs", "Pydantic"],
        "career_paths": ["Backend Developer", "API Engineer", "Python Developer"],
        "employability_index": 0.81,
    },
    {
        "id": "GENAI", "name": "Generative AI", "credits": 4,
        "min_cgpa": 7.5, "max_backlog": 0, "last_date": "Aug 10, 2026", "seats": 50,
        "tags": ["generative ai", "genai", "llm", "prompt engineering", "transformers"],
        "skills_taught": ["LLMs", "Prompt Engineering", "Transformers", "Fine-tuning", "RAG"],
        "career_paths": ["AI Engineer", "ML Engineer", "GenAI Developer"],
        "employability_index": 0.92,
    },
    {
        "id": "ML", "name": "Machine Learning", "credits": 4,
        "min_cgpa": 7.0, "max_backlog": 1, "last_date": "Aug 11, 2026", "seats": 65,
        "tags": ["machine learning", "ml", "supervised learning", "python", "statistics"],
        "skills_taught": ["Python", "Supervised Learning", "Unsupervised Learning", "Model Evaluation", "Scikit-learn"],
        "career_paths": ["ML Engineer", "Data Scientist", "Applied Scientist"],
        "employability_index": 0.89,
    },
    {
        "id": "DATAANALYTICS", "name": "Data Analytics", "credits": 3,
        "min_cgpa": 6.0, "max_backlog": 2, "last_date": "Aug 16, 2026", "seats": 90,
        "tags": ["data analytics", "analytics", "statistics", "excel", "visualization"],
        "skills_taught": ["Excel", "SQL", "Statistics", "Data Visualization", "Python"],
        "career_paths": ["Data Analyst", "Business Analyst", "Reporting Analyst"],
        "employability_index": 0.77,
    },
    {
        "id": "IOT", "name": "Internet of Things", "credits": 3,
        "min_cgpa": 6.0, "max_backlog": 2, "last_date": "Aug 15, 2026", "seats": 55,
        "tags": ["iot", "internet of things", "embedded", "sensors", "microcontrollers"],
        "skills_taught": ["Embedded C", "Sensors", "Microcontrollers", "MQTT", "Edge Computing"],
        "career_paths": ["IoT Engineer", "Embedded Systems Engineer", "Hardware Engineer"],
        "employability_index": 0.73,
    },
    {
        "id": "DWDM", "name": "Data Warehousing & Data Mining", "credits": 3,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 14, 2026", "seats": 60,
        "tags": ["data warehousing", "data mining", "etl", "olap", "big data"],
        "skills_taught": ["ETL", "OLAP", "Data Mining", "Clustering", "Association Rules"],
        "career_paths": ["Data Engineer", "BI Developer", "Data Warehouse Analyst"],
        "employability_index": 0.75,
    },
    {
        "id": "OS", "name": "Operating Systems", "credits": 4,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 12, 2026", "seats": 90,
        "tags": ["operating systems", "os", "processes", "memory management", "concurrency"],
        "skills_taught": ["Process Scheduling", "Memory Management", "Concurrency", "File Systems", "Threads"],
        "career_paths": ["Systems Engineer", "Kernel Developer", "Backend Engineer"],
        "employability_index": 0.80,
    },
    {
        "id": "ACA", "name": "Advanced Computer Architecture", "credits": 4,
        "min_cgpa": 7.0, "max_backlog": 1, "last_date": "Aug 11, 2026", "seats": 45,
        "tags": ["computer architecture", "pipelining", "cache", "parallel computing"],
        "skills_taught": ["Pipelining", "Cache Optimization", "Parallel Computing", "Instruction Sets"],
        "career_paths": ["Hardware Engineer", "Performance Engineer", "Systems Architect"],
        "employability_index": 0.74,
    },
    {
        "id": "DAA", "name": "Design & Analysis of Algorithms", "credits": 4,
        "min_cgpa": 7.5, "max_backlog": 0, "last_date": "Aug 10, 2026", "seats": 60,
        "tags": ["algorithms", "daa", "complexity analysis", "greedy", "divide and conquer"],
        "skills_taught": ["Algorithm Design", "Complexity Analysis", "Greedy Algorithms", "Divide & Conquer", "NP-Completeness"],
        "career_paths": ["Software Engineer", "SDE", "Competitive Programmer"],
        "employability_index": 0.87,
    },
    {
        "id": "ROBOTICS", "name": "Robotics", "credits": 3,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 13, 2026", "seats": 40,
        "tags": ["robotics", "automation", "control systems", "sensors", "kinematics"],
        "skills_taught": ["Kinematics", "Control Systems", "Sensors", "ROS", "Automation"],
        "career_paths": ["Robotics Engineer", "Automation Engineer", "Mechatronics Engineer"],
        "employability_index": 0.76,
    },
    {
        "id": "VISUALPROG", "name": "Visual Programming", "credits": 3,
        "min_cgpa": 5.5, "max_backlog": 2, "last_date": "Aug 16, 2026", "seats": 70,
        "tags": ["visual programming", "gui", "desktop apps", "event driven"],
        "skills_taught": ["GUI Design", "Event-Driven Programming", "C#", ".NET", "Desktop App Development"],
        "career_paths": ["Desktop App Developer", "Software Engineer", "UI Developer"],
        "employability_index": 0.68,
    },
    {
        "id": "NETWORKS", "name": "Computer Networks", "credits": 4,
        "min_cgpa": 6.5, "max_backlog": 1, "last_date": "Aug 12, 2026", "seats": 75,
        "tags": ["computer networks", "networking", "tcp/ip", "protocols"],
        "skills_taught": ["TCP/IP", "Routing", "Network Security Basics", "Protocols", "Subnetting"],
        "career_paths": ["Network Engineer", "Network Administrator", "Security Engineer"],
        "employability_index": 0.75,
    },
    {
        "id": "COMPILERS", "name": "Compiler Design", "credits": 4,
        "min_cgpa": 7.5, "max_backlog": 0, "last_date": "Aug 10, 2026", "seats": 35,
        "tags": ["compiler design", "compilers", "parsing", "lexical analysis"],
        "skills_taught": ["Lexical Analysis", "Parsing", "Syntax Trees", "Code Generation", "Optimization"],
        "career_paths": ["Compiler Engineer", "Language Designer", "Systems Programmer"],
        "employability_index": 0.78,
    },
    {
        "id": "GRAPHICS", "name": "Computer Graphics", "credits": 3,
        "min_cgpa": 6.0, "max_backlog": 2, "last_date": "Aug 15, 2026", "seats": 50,
        "tags": ["computer graphics", "rendering", "3d", "opengl", "animation"],
        "skills_taught": ["OpenGL", "Rendering", "3D Transformations", "Shading", "Animation"],
        "career_paths": ["Graphics Engineer", "Game Developer", "Visualization Engineer"],
        "employability_index": 0.73,
    },
]

COURSE_BY_ID = {c["id"]: c for c in COURSES}

DEPARTMENTS = [
    "Computer Science",
    "Information Technology",
    "Electronics",
    "Mechanical",
    "Civil",
]

# Skills a working professional is generally expected to have in each
# career path -- used for skill-gap analysis and resume matching.
CAREER_REQUIRED_SKILLS = {
    "AIML":       ["Python", "Machine Learning", "Deep Learning", "Statistics", "SQL", "Neural Networks"],
    "DS":         ["Python", "SQL", "Statistics", "Data Visualization", "Excel", "Pandas"],
    "WEB":        ["HTML", "CSS", "JavaScript", "React", "Node.js", "Git", "REST APIs"],
    "CYB":        ["Network Security", "Linux", "Cryptography", "Ethical Hacking", "Risk Analysis", "Python"],
    "CLOUD":      ["AWS", "Docker", "Kubernetes", "Linux", "CI/CD", "Python"],
    "FULLSTACK":  ["React", "Node.js", "JavaScript", "MongoDB", "REST APIs", "Git", "SQL"],
    "BACKEND":    ["Python", "Java", "SQL", "REST APIs", "System Design", "Git"],
    "DEVOPS":     ["Docker", "Kubernetes", "CI/CD", "Terraform", "Linux", "Jenkins"],
    "ANALYTICS":  ["Excel", "SQL", "Power BI", "Tableau", "Statistics"],
    "MOBILE":     ["Flutter", "React Native", "Kotlin", "REST APIs", "Git"],
    "UIUX":       ["Figma", "Wireframing", "Prototyping", "User Research"],
    "BLOCKCHAIN": ["Solidity", "Smart Contracts", "Ethereum", "Web3.js", "Cryptography"],
    "PHYSICS":    ["Classical Mechanics", "Electromagnetism", "Thermodynamics"],
    "MATHS":      ["Calculus", "Linear Algebra", "Probability", "Discrete Mathematics"],
    "CPROG":      ["C", "Pointers", "Memory Management", "Debugging"],
    "CPP":        ["C++", "OOP", "STL", "Data Structures"],
    "JAVA":       ["Java", "OOP", "Spring Boot", "JVM"],
    "PYTHON":     ["Python", "OOP", "Scripting", "Automation"],
    "DSA":        ["Arrays", "Trees", "Graphs", "Dynamic Programming", "Algorithm Design"],
    "FLASK":      ["Flask", "Python", "REST APIs", "SQLAlchemy", "Jinja2"],
    "FRONTEND":   ["HTML", "CSS", "JavaScript", "React", "Responsive Design"],
    "SQL":        ["SQL", "Joins", "Indexing", "Query Optimization"],
    "OOP":        ["OOP", "Design Patterns", "Encapsulation", "Inheritance", "Polymorphism"],
    "DBMS":       ["DBMS", "Normalization", "SQL", "Transactions", "Indexing"],
    "SWE":        ["SDLC", "Agile", "Testing", "Requirements Analysis", "UML"],
    "SYSDESIGN":  ["System Design", "Scalability", "Load Balancing", "Distributed Systems", "Caching"],
    "DOCKER":     ["Docker", "Containerization", "Docker Compose", "Images"],
    "FASTAPI":    ["FastAPI", "Python", "Async Programming", "REST APIs", "Pydantic"],
    "GENAI":      ["LLMs", "Prompt Engineering", "Transformers", "Fine-tuning", "RAG"],
    "ML":         ["Python", "Supervised Learning", "Unsupervised Learning", "Model Evaluation", "Scikit-learn"],
    "DATAANALYTICS": ["Excel", "SQL", "Statistics", "Data Visualization", "Python"],
    "IOT":        ["Embedded C", "Sensors", "Microcontrollers", "MQTT", "Edge Computing"],
    "DWDM":       ["ETL", "OLAP", "Data Mining", "Clustering", "Association Rules"],
    "OS":         ["Process Scheduling", "Memory Management", "Concurrency", "File Systems", "Threads"],
    "ACA":        ["Pipelining", "Cache Optimization", "Parallel Computing", "Instruction Sets"],
    "DAA":        ["Algorithm Design", "Complexity Analysis", "Greedy Algorithms", "Divide & Conquer", "NP-Completeness"],
    "ROBOTICS":   ["Kinematics", "Control Systems", "Sensors", "ROS", "Automation"],
    "VISUALPROG": ["GUI Design", "Event-Driven Programming", "C#", ".NET", "Desktop App Development"],
    "NETWORKS":   ["TCP/IP", "Routing", "Network Security Basics", "Protocols", "Subnetting"],
    "COMPILERS":  ["Lexical Analysis", "Parsing", "Syntax Trees", "Code Generation", "Optimization"],
    "GRAPHICS":   ["OpenGL", "Rendering", "3D Transformations", "Shading", "Animation"],
}

# Master skill vocabulary the resume analyzer scans for.
ALL_KNOWN_SKILLS = sorted(set(
    skill for skills in CAREER_REQUIRED_SKILLS.values() for skill in skills
) | {
    "Java", "C++", "TensorFlow", "PyTorch", "Django", "Flask", "MongoDB", "Excel",
    "Git", "Tableau", "Power BI", "Terraform", "Jenkins", "Kotlin", "Swift",
    "Figma", "Solidity", "GraphQL", "Redis", "PostgreSQL",
})